### ISSUE TITLE
No longer works on Oculus

### ISSUE THREAD

**Issue by RiverExplorer** [oculus-samples/Unity-SharedSpaces#22] opened 2023-04-08 22:40 UTC
It compiles and runs just fine on Win64.
The Android/Oculus build compiles and links fine. HOWEVER it just produces a white screen and nothing else. ADB produced a few hundred error messages, among them null variable errors with no object references, file names, or line numbers. Impossible to debug.

**Comment by AlexThiv** [comment] 2023-04-11 22:30
It looks like you might have an entitlement issue where the user on the device might not be entitled to use the app, if so you will see it in the logs.
You can get the logs only for unity using this command: `logcat -s Unity`

Following the steps to use the appId from [configuration](https://github.com/oculus-samples/Unity-SharedSpaces#c-oculus-application-configuration) and making sure that the user on the device has access to the app (you can navigate to the product page to check if you have access) should solve the issue.

If you still have issues, you can send us the Unity logs so we can have a better understanding of what is going on.

**Comment by MikeFesta** [comment] 2023-04-24 03:07
I ran into this issue as well (the app is just a white void) and I got it working by publishing the app to the Alpha release channel and downloading + installing it from the store. I also had to specifically add my user account and test accounts to the Alpha release channel.

It threw me off because up until now, I hadn't pushed any apps through App Distribution and would normally just run from the Unity editor with Quest Link or build and run on the device. It would be helpful if additional steps were mentioned in part C of the readme, as it currently ends at step 3. Data Usage Checkup.

It should have a part 4 with these steps:
- Create a store-compatible AndroidManifest.xml https://developer.oculus.com/resources/publish-mobile-manifest/
- Create a new Android Project Keystore https://developer.oculus.com/resources/publish-mobile-app-signing/
- Upload the .apk to the Alpha Release channel using the Meta Quest Developer Hub
- Add your developer account and any other user or test user accounts to the Alpha Release channel. https://developer.oculus.com/resources/publish-release-channels-add-users/
- Install the app through the Store on the device. You have to go to the Store app and search for the exact name that you gave your project. It doesn't work when running it from "Untrusted Sources" as you would normally at the start of development.

**Comment by AlexThiv** [comment] 2023-05-02 22:48
We are currently looking into this issue. @MikeFesta solution is the current work around for the moment.

**Comment by RiverExplorer** [comment] 2023-05-10 19:31
It was a some of that. Seems you have to setup up a meta RIFT -AND- Quest app, and each has to has destinations. If I do not also do the RIFT, it fails to work. I just wanted it to work on the Quest.

> It looks like you might have an entitlement issue where the user on the device might not be entitled to use the app, if so you will see it in the logs. You can get the logs only for unity using this command: `logcat -s Unity`
> 
> Following the steps to use the appId from [configuration](https://github.com/oculus-samples/Unity-SharedSpaces#c-oculus-application-configuration) and making sure that the user on the device has access to the app (you can navigate to the product page to check if you have access) should solve the issue.
> 
> If you still have issues, you can send us the Unity logs so we can have a better understanding of what is going on.

**Comment by RiverExplorer** [comment] 2023-05-10 19:33
This last part seems to change. Some get an email, they have to click on the link. The instructions in the email do not match the web page it takes them to. And for others, within minutes of them being added (or accepting the test invitation), it shows up in their owned, but not installed apps.

And for others they have to search for it and manually install it.

And others get an email with a bogus link.


>     * Install the app through the Store on the device. You have to go to the Store app and search for the exact name that you gave your project. It doesn't work when running it from "Untrusted Sources" as you would normally at the start of development.

**Comment by AlexThiv** [comment] 2023-05-16 22:22
Thanks for the details!

For the entitlement issue, could you install the latest OS and let us know if you still run into this issue.

As for the RIFT app Id, this is only used when testing in Editor, like when using Link or building a windows build.

We will take a look at the email issue you are reporting. Can you give us an example of what is wrong with the link provided in the email?

**Comment by radem-bd** [comment] 2023-05-27 00:11
> I ran into this issue as well (the app is just a white void) and I got it working by publishing the app to the Alpha release channel and downloading + installing it from the store. I also had to specifically add my user account and test accounts to the Alpha release channel.

> * Install the app through the Store on the device. You have to go to the Store app and search for the exact name that you gave your project. It doesn't work when running it from "Untrusted Sources" as you would normally at the start of development.

@MikeFesta I am also having the same issue with the void white space when the app is launched directly from Unity or Meta Quest Dev Hub. I followed your pointers to fill in the gaps I had but I am not able to find my sample app in the store. I only see official apps/games. Did you submit your sample app to Meta for the official release? Also, can you clarify what you mean ` exact name that you gave your project`? Are you referring to the name of the app or the Unity project? Tagging @AlexThiv for visibility also

**Comment by radem-bd** [comment] 2023-05-27 00:23
>  I am not able to find my sample app in the store. I only see official apps/games.

Ahh, I needed to enable the developer feed in the store app to find my sample app. I was able to find my app by searching for the app name itself. It shows up under App Lab. Launching the app, I still see the same void white space :( @AlexThiv Can you help?

**Comment by AlexThiv** [comment] 2023-05-27 00:25
@radem-bd could you send us the logs you get when the app launches
`logcat -s Unity`

**Comment by radem-bd** [comment] 2023-05-27 01:01
> @radem-bd could you send us the logs you get when the app launches `logcat -s Unity`

@AlexThiv 
$ adb logcat -s Unity
--------- beginning of main
05-26 20:59:27.097 21128 21146 I Unity   : MemoryManager: Using 'Dynamic Heap' Allocator.
05-26 20:59:27.114 21128 21146 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 3, Memory = 11829mb
05-26 20:59:27.114 21128 21146 I Unity   : SystemInfo ARM big.LITTLE configuration: 3 big (mask: 0x70), 0 little (mask: 0x0)
05-26 20:59:27.114 21128 21146 I Unity   : XR UsableCoreMask: 0x70
05-26 20:59:27.114 21128 21146 I Unity   : ApplicationInfo com.samples.radem.sharedspaces version 1.1.0
05-26 20:59:27.114 21128 21146 I Unity   : Built from '2021.3/staging' branch, Version '2021.3.21f1 (1b156197d683)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
05-26 20:59:27.279 21128 21146 I Unity   : Company Name: Oculus
05-26 20:59:27.279 21128 21146 I Unity   : Product Name: SharedSpaces
05-26 20:59:27.281 21128 21146 D Unity   : loading library OVRPlugin
05-26 20:59:27.531 21128 21146 I Unity   : XRGeneral Settings awakening...
05-26 20:59:27.531 21128 21146 I Unity   : UnityEngine.XR.Management.XRGeneralSettings:Awake()
05-26 20:59:27.531 21128 21146 I Unity   : 
05-26 20:59:27.746 21128 21146 W Unity   : Orientation Listener cannot detect orientation.
05-26 20:59:27.756 21128 21146 D Unity   : initOculus Java!
05-26 20:59:27.756 21128 21128 D Unity   : Oculus UI thread done.
05-26 20:59:28.132 21128 21146 W Unity   : Ignoring depth surface store action as it is memoryless
05-26 20:59:32.325 21128 21146 I Unity   : Unity v2021.3.21f1, Oculus Utilities v1.81.0, OVRPlugin v1.81.0, SDK v1.0.25.
05-26 20:59:32.325 21128 21146 I Unity   : OVRManager:InitOVRManager()
05-26 20:59:32.325 21128 21146 I Unity   : 
05-26 20:59:32.327 21128 21146 I Unity   : SystemHeadset Meta_Quest_Pro, API OpenXR
05-26 20:59:32.327 21128 21146 I Unity   : OVRManager:InitOVRManager()
05-26 20:59:32.327 21128 21146 I Unity   : 
05-26 20:59:32.328 21128 21146 I Unity   : OpenXR instance 0x100000000000002 session 0x200000000000020
05-26 20:59:32.328 21128 21146 I Unity   : OVRManager:InitOVRManager()
05-26 20:59:32.328 21128 21146 I Unity   : 
05-26 20:59:32.332 21128 21146 I Unity   : OVRPlugin.Media initialized
05-26 20:59:32.332 21128 21146 I Unity   : OVRManager:StaticInitializeMixedRealityCapture(OVRMixedRealityCaptureConfiguration)
05-26 20:59:32.332 21128 21146 I Unity   : OVRManager:InitOVRManager()
05-26 20:59:32.332 21128 21146 I Unity   : 
05-26 20:59:32.333 21128 21146 I Unity   : [MRC] SetMrcAudioSampleRate(48000)
05-26 20:59:32.333 21128 21146 I Unity   : OVRManager:StaticInitializeMixedRealityCapture(OVRMixedRealityCaptureConfiguration)
05-26 20:59:32.333 21128 21146 I Unity   : OVRManager:InitOVRManager()
05-26 20:59:32.333 21128 21146 I Unity   : 
05-26 20:59:32.335 21128 21146 I Unity   : [MRC] Active InputVideoBufferType:TextureHandle
05-26 20:59:32.335 21128 21146 I Unity   : OVRManager:StaticInitializeMixedRealityCapture(OVRMixedRealityCaptureConfiguration)
05-26 20:59:32.335 21128 21146 I Unity   : OVRManager:InitOVRManager()
05-26 20:59:32.335 21128 21146 I Unity   : 
05-26 20:59:32.336 21128 21146 I Unity   : [MRC] ActivateMode: Automatic
05-26 20:59:32.336 21128 21146 I Unity   : OVRManager:StaticInitializeMixedRealityCapture(OVRMixedRealityCaptureConfiguration)
05-26 20:59:32.336 21128 21146 I Unity   : OVRManager:InitOVRManager()
05-26 20:59:32.336 21128 21146 I Unity   : 
05-26 20:59:32.341 21128 21146 I Unity   : Current display frequency 72, available frequencies [72, 72, 80, 80, 90, 90]
05-26 20:59:32.341 21128 21146 I Unity   : OVRManager:InitOVRManager()
05-26 20:59:32.341 21128 21146 I Unity   : 
05-26 20:59:32.418 21128 21146 I Unity   : OVRControllerHelp: Active controller type: TouchPro for product Oculus Quest (headset Meta_Quest_Pro, hand HandRight)
05-26 20:59:32.418 21128 21146 I Unity   : OVRControllerHelper:InitializeControllerModels()
05-26 20:59:32.418 21128 21146 I Unity   : 
05-26 20:59:32.420 21128 21146 I Unity   : OVRControllerHelp: Active controller type: TouchPro for product Oculus Quest (headset Meta_Quest_Pro, hand HandLeft)
05-26 20:59:32.420 21128 21146 I Unity   : OVRControllerHelper:InitializeControllerModels()
05-26 20:59:32.420 21128 21146 I Unity   : 
05-26 20:59:32.430 21128 21146 I Unity   : [OVRManager] HMDAcquired event
05-26 20:59:32.430 21128 21146 I Unity   : OVRManager:Update()
05-26 20:59:32.430 21128 21146 I Unity   : 
05-26 20:59:32.431 21128 21146 I Unity   : [OVRManager] HMDMounted event
05-26 20:59:32.431 21128 21146 I Unity   : OVRManager:Update()
05-26 20:59:32.431 21128 21146 I Unity   : 
05-26 20:59:32.432 21128 21146 I Unity   : [OVRManager] VrFocusAcquired event
05-26 20:59:32.432 21128 21146 I Unity   : OVRManager:Update()
05-26 20:59:32.432 21128 21146 I Unity   : 
05-26 20:59:32.435 21128 21146 I Unity   : [OVRManager] TrackingAcquired event
05-26 20:59:32.435 21128 21146 I Unity   : OVRManager:Update()
05-26 20:59:32.435 21128 21146 I Unity   : 
05-26 20:59:32.460 21128 21146 W Unity   : Ignoring depth surface store action as it is memoryless
05-26 20:59:32.467 21128 21146 I Unity   : Recenter event detected
05-26 20:59:32.467 21128 21146 I Unity   : OVRDisplay:Update()
05-26 20:59:32.467 21128 21146 I Unity   : OVRManager:Update()
05-26 20:59:32.467 21128 21146 I Unity   : 
05-26 20:59:32.568 21128 21146 I Unity   : Oculus Platform SDK initialized successfully
05-26 20:59:32.568 21128 21146 I Unity   : SharedSpacesApplication:OnOculusPlatformInitialized(Message`1)
05-26 20:59:32.568 21128 21146 I Unity   : Oculus.Platform.Callback:HandleMessage(Message)
05-26 20:59:32.568 21128 21146 I Unity   : Oculus.Platform.Callback:RunCallbacks()
05-26 20:59:32.568 21128 21146 I Unity   : 
05-26 20:59:32.647 21128 21146 E Unity   : An unknown error occurred. Request failed.
05-26 20:59:32.647 21128 21146 E Unity   : Oculus.Platform.Request`1:OnComplete(Callback)
05-26 20:59:32.647 21128 21146 E Unity   : Oculus.Platform.Callback:HandleMessage(Message)
05-26 20:59:32.647 21128 21146 E Unity   : Oculus.Platform.Callback:RunCallbacks()
05-26 20:59:32.647 21128 21146 E Unity   :

**Comment by AlexThiv** [comment] 2023-05-27 03:01
Thanks we will look into trying to reproduce the error. In the mean time can you validate that you have all the Data Use Checkup approved
![image](https://github.com/oculus-samples/Unity-SharedSpaces/assets/46505821/220cb84f-ab92-4cdc-8ed4-0cd9d2efe37e)

And secondly that the device launching the application is logged in as either a member of the organization
![image](https://github.com/oculus-samples/Unity-SharedSpaces/assets/46505821/98861473-0113-4dc5-a786-8e39122032e3)

Or is added to the channel you are using on the app for Quest
![image](https://github.com/oculus-samples/Unity-SharedSpaces/assets/46505821/2b55f0b9-4e8c-415d-b727-ff8a88806474)
![image](https://github.com/oculus-samples/Unity-SharedSpaces/assets/46505821/0d1d65f8-1e39-4fe6-b0e1-4aa580c9e05e)
![image](https://github.com/oculus-samples/Unity-SharedSpaces/assets/46505821/82997a89-1166-42b3-a368-c02cb9523720)

**Comment by radem-bd** [comment] 2023-05-27 20:17
> Thanks we will look into trying to reproduce the error. In the meantime can you validate that you have all the Data Use Checkup approved !

@AlexThiv Thanks! I had my data use checkup ready for approval but I did not know where developers are expected to obtain a Privacy Policy URL. I got stuck there, and it was not clear if that was required so I proceeded without it. If that is indeed the culprit for the white void scene, please let me know how I can obtain the Privacy Policy URL. 

> And secondly that the device launching the application is logged in as either a member of the organization

I have the appropriate user launching the app.

**Comment by radem-bd** [comment] 2023-05-27 20:46
> how I can obtain the Privacy Policy URL.

Read some pointers provided here https://developers.facebook.com/blog/post/2022/06/14/building-your-multiplayer-vr-experience-sharedspaces-sample-unity. 

```
Once you submit, you’ll be asked to provide a 
[Privacy Policy URL](https://developer.oculus.com/policy/privacy-policy/).
 (If you fork the project, you can add a privacy policy markdown file and link to that.) 
After you provide the Privacy Policy URL, the 
requested platform features will be indicated as “approved,” as shown in the image below.
```

I got my data use checkup approved and I am happy to report that I see all the destinations including my Avatar. I was able to explore the rooms as well. I noticed I am not able to create a link to allow another user to join the shared spaces. I will create a new issue for that with logs. Thanks for your help @AlexThiv

**Comment by jasonmeisel** [comment] 2023-06-20 22:25
Seems like this is resolved, so I'm going to close the issue. If you continue to have issues getting entitlement, please let us know.

**Closed as completed by jasonmeisel** 2023-06-20 22:25 UTC
