### ISSUE TITLE
cant see both players at the same time even though i have a metaquest2 and metaquest3 logged in

### ISSUE THREAD

**Issue by juansuerorobotics** [oculus-samples/Unity-SharedSpaces#30] opened 2024-02-12 18:46 UTC

**Comment by juansuerorobotics** [comment] 2024-02-13 03:43
turns out you can only multiplayer a meta quest 3 with another meta quest 3.   its tricky because 95% of things seem to flow across both headsets.. like your friends list and invites through the platform.   but inside the actual game you cannot see the other players avatar and that bug happens right before the code to show the other players avatar.. so any calls after that to go through the photon network never happen

**Comment by jasonmeisel** [comment] 2024-02-16 01:02
We're not able to reproduce this issue on our end. Could you provide logs from both devices using `adb logcat -s Unity`? Also, which lines of code are you referring to when you say "the code to show the other players avatar"? Thanks!

**Comment by juansuerorobotics** [comment] 2024-02-16 16:47
ive attached the logs below.

to summary when i start both apps on both headsets then go to headset1 and "invite user" that seems to work fine, the meta quest UI comes up and lets me see my friend who is online.  same thing on the meta quest 2.
then i send out the invite from meta quest 3
the meta quest 2 beeps and i can see i can accept the invite but then it says "Room is not available right now or something similar.  and it asks me would i like to see more details about the invite.. when i click to see the details the UI from the meta quest breifly flashes something that looks like the "people" interface but then it crashes.  same thing happens on the meta quest 3 so its happening on both headsets.  both will say the room is not accessible or not available and when i click on the "more details about the invite" the UI crashes.    But the Unity app keeps playing itself.

[headset1_mq3.txt](https://github.com/oculus-samples/Unity-SharedSpaces/files/14313590/headset1_mq3.txt)

[headset2_mq2.txt](https://github.com/oculus-samples/Unity-SharedSpaces/files/14313597/headset2_mq2.txt)

**Comment by juansuerorobotics** [comment] 2024-02-17 13:40
as i mentioned this works across meta quest 3s  but not when one is a meta quest 3 and one is a meta quest 2.   this is the oculus share spaces for unity straight from the applab not my own upload.



This screenshot is result after accepting the invitation the oculus UI says location not available.
By the way im using a couple of Tripods with Head Mannequin Head to keep the headsets from falling asleep while i put one down to use another one.
![Screenshot 2024-02-17 083524](https://github.com/oculus-samples/Unity-SharedSpaces/assets/91294552/1c81f020-e251-4afd-a0cd-9d4595eb21ba)


Here is the people oculus UI that crashes after selecting to view more details about the invitation to a room that is not available.
![Screenshot 2024-02-17 083923](https://github.com/oculus-samples/Unity-SharedSpaces/assets/91294552/2de75b2b-090b-4cc7-87c4-cd5a37d47f97)


Tripod with Head Mannequin Head
![Screenshot 2024-02-17 084650](https://github.com/oculus-samples/Unity-SharedSpaces/assets/91294552/e3febdf5-2a6a-420a-a7e5-e65a16b6ca92)


Video proof
https://github.com/oculus-samples/Unity-SharedSpaces/assets/91294552/3bd5ee45-6c5e-4fa4-b49d-36d794668693

**Comment by AlexThiv** [comment] 2024-02-20 23:23
Thanks for the additional info, we are looking into this invite issue.

**Comment by AlexThiv** [comment] 2024-06-11 21:31
@juansuerorobotics this should be resolved with the latest os release. Can you validate if you can reproduce the issue?

**Closed as completed** 2024-07-02 22:25 UTC
